[package]
name = "bevy-ray-marching"
version = "0.1.0"
edition = "2021"

[dependencies]
#bevy = { git = "https://github.com/bevyengine/bevy.git" }
bevy = "0.10"
bevy_egui = "0.20"
log = "0.4"
nalgebra = "0.32.2"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"